apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gk-audit-service-type
  annotations:
    policy.open-cluster-management.io/standards: Securité applications
    policy.open-cluster-management.io/categories: Gatekeeper Constraints
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-gk-audit-service-type
      spec:
        remediationAction: inform
        severity: high
        object-templates:

          - complianceType: musthave
            objectDefinition:

              apiVersion: constraints.gatekeeper.sh/v1beta1
              kind: K8sCFServiceType
              metadata:
                name: k8scfservicetype
              status:
                totalViolations: 0
